version : '3.7'
services:
  NTG:
    image: jenkins:1.0
    container_name: Jenkins
    restart: unless-stopped
    ports:
      - 9640:8080
      - 50001:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
        #- /var/run/docker.sock:/var/run/docker.sock
        #- /usr/bin/docker:/usr/bin/docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1



volumes:
  jenkins_home:
    driver: local
  jenkins-docker-certs:
    driver: local



